# Generated by Django 5.1.4 on 2025-01-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_issue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.CharField(default='team A', max_length=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='logged_time',
            field=models.FloatField(default=0),
        ),
    ]
