# Generated by Django 5.1.4 on 2025-01-07 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_issue_asigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='issues',
            field=models.ManyToManyField(blank=True, to='authentication.issue'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='asigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
