# Generated by Django 3.2.12 on 2025-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_issues_alter_issue_asigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='asigned',
            new_name='assigned',
        ),
        migrations.AlterField(
            model_name='issue',
            name='priorities',
            field=models.CharField(choices=[('Highest', 'Highest'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low'), ('Lowest', 'Lowest')], default='Low', max_length=20),
        ),
    ]
